### PR TITLE
Fixed Formatting

### PR DESCRIPTION
**Pull request by mortdudley**

### CODE REVIEW

**Comment by mortdudley** [comment]
Also added a noClip logic

**Comment by ScrachStack** [comment]
> Also added a noClip logic

image
where do I mention that the anticheat can do any of these and I haven't I said it isn't done 
image

**Comment by ScrachStack** [comment]
also has this noclip been tested also curious on how the formatting looks like its 'pasted' from somewhere because formatting has nothing to do with how the code runs and the formatting looks fine other then a few indents.

**Comment by mortdudley** [comment]
The options are there in the config.lua. It's not a stretch to assume that the features should be in place if they are able to be configured. An alternative would be to leave a comment next to the config option to say "coming soon" or something like that. Not trying to have a go at you or anything, but some people will download and use this resource assuming that it provides features that it currently doesn't, I just don't want it leading to any confusion and thought I could lend a hand.

The noClip detection works. I've been using it on my server for a long time.

**Comment by ScrachStack** [comment]
im not either but im still curious ...

**Comment by ScrachStack** [comment]
but also everything in the config is planned to be added

**Comment by mortdudley** [comment]
That's cool and all, it's just best to do what you can to ensure people aren't getting mad at you for thinking there are features that aren't actually ready yet. I'm happy to help if you need any

**Pull request merged**
